<?php

/**
 * @file
 * Contains cache.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cache_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cache module.
    case 'help.page.cache':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cache expirements') . '</p>';
      return $output;

    default:
  }
}
