<?php

/**
 * @file
 * Contains certification.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function certification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the certification module.
    case 'help.page.certification':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module dev api examples') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function certification_theme() {
  return [
    'certification' => [
      'render element' => 'children',
    ],
  ];
}
